ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password VARCHAR(100),
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(50),
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(50),
    ADD COLUMN IF NOT EXISTS age INT,
    ADD COLUMN IF NOT EXISTS address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS city VARCHAR(100);
