ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS users_id_seq;
ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
CREATE SEQUENCE users_id_seq AS BIGINT START WITH 1 OWNED BY users.id;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq'::regclass);
